// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v5.29.3
// source: proto/auth.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export enum UserRole {
  USER = 0,
  OPERATOR = 1,
  AUDITOR = 2,
  ADMIN = 3,
  UNRECOGNIZED = -1,
}

export interface User {
  email: string;
  role: number;
  createdAt: string;
  updatedAt: string;
}

export interface TokenPayload {
  sub: string;
  email: string;
  role: number;
  tokenVersion: number;
  type: string;
}

export interface CreateUserRequest {
  email: string;
  password: string;
  role: UserRole;
}

export interface CreateUserResponse {
  email: string;
  role: number;
}

export interface SigninUserRequest {
  email: string;
  password: string;
}

export interface SigninUserResponse {
  accessToken: string;
  refreshToken: string;
}

export interface FindUsersRequest {
}

export interface FindUsersResponse {
  users: User[];
}

export interface VerifyTokenRequest {
  jwtToken: string;
  isRefresh: boolean;
}

export interface VerifyTokenResponse {
  verify: boolean;
  payload: TokenPayload | undefined;
}

export interface UpdateUserRequest {
  email: string;
  role: UserRole;
}

export interface UpdateUserResponse {
  email: string;
  role: UserRole;
}

export interface RefreshTokenRequest {
  userId: string;
}

export interface RefreshTokenResponse {
  accessToken: string;
  refreshToken: string;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface AuthServiceClient {
  createUser(request: CreateUserRequest, metadata?: Metadata): Observable<CreateUserResponse>;

  signinUser(request: SigninUserRequest, metadata?: Metadata): Observable<SigninUserResponse>;

  findUsers(request: FindUsersRequest, metadata?: Metadata): Observable<FindUsersResponse>;

  verifyToken(request: VerifyTokenRequest, metadata?: Metadata): Observable<VerifyTokenResponse>;

  updateUser(request: UpdateUserRequest, metadata?: Metadata): Observable<UpdateUserResponse>;

  refreshToken(request: RefreshTokenRequest, metadata?: Metadata): Observable<RefreshTokenResponse>;
}

export interface AuthServiceController {
  createUser(
    request: CreateUserRequest,
    metadata?: Metadata,
  ): Promise<CreateUserResponse> | Observable<CreateUserResponse> | CreateUserResponse;

  signinUser(
    request: SigninUserRequest,
    metadata?: Metadata,
  ): Promise<SigninUserResponse> | Observable<SigninUserResponse> | SigninUserResponse;

  findUsers(
    request: FindUsersRequest,
    metadata?: Metadata,
  ): Promise<FindUsersResponse> | Observable<FindUsersResponse> | FindUsersResponse;

  verifyToken(
    request: VerifyTokenRequest,
    metadata?: Metadata,
  ): Promise<VerifyTokenResponse> | Observable<VerifyTokenResponse> | VerifyTokenResponse;

  updateUser(
    request: UpdateUserRequest,
    metadata?: Metadata,
  ): Promise<UpdateUserResponse> | Observable<UpdateUserResponse> | UpdateUserResponse;

  refreshToken(
    request: RefreshTokenRequest,
    metadata?: Metadata,
  ): Promise<RefreshTokenResponse> | Observable<RefreshTokenResponse> | RefreshTokenResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createUser",
      "signinUser",
      "findUsers",
      "verifyToken",
      "updateUser",
      "refreshToken",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
